### ISSUE TITLE
Deriving Eq for reflection syntax extremely slow

### ISSUE THREAD

**Issue by jespercockx** [UlfNorell/agda-prelude#4]
Below is the code for deriving Eq on the reflected syntax. It's working, but it's extremely slow. I'm not sure if it is due to Agda or the implementation of derivingEq though.

    open import Prelude
    open import Data.List
    open import Builtin.Reflection
    open import Tactic.Deriving.Eq

    unquoteDecl eqAny = derivingEq (quote Any) eqAny
    instance 
      EqAny : ∀ {a b} {A : Set a} {B : A → Set b} {l : List A} → 
              {{_ : Eq A}} {{_ : ∀ {x} → Eq (B x)}} → Eq (Any B l)
      EqAny = record { _==_ = eqAny }

    unquoteDecl eq≡ = derivingEq (quote _≡_) eq≡

    unquoteDecl eqVisibility = derivingEq (quote Visibility) eqVisibility

    instance
      EqVisibility : Eq Visibility
      EqVisibility = record { _==_ = eqVisibility }

    unquoteDecl eqRelevance = derivingEq (quote Relevance) eqRelevance

    instance
      EqRelevance : Eq Relevance
      EqRelevance = record { _==_ = eqRelevance }

    instance
      Eq≡ : ∀ {a} {A : Set a} {x y : A} {{_ : Eq A}} → Eq (x ≡ y)
      Eq≡ = record { _==_ = eq≡ }

    unquoteDecl eqArgInfo = derivingEq (quote ArgInfo) eqArgInfo

    instance
      EqArgInfo : Eq ArgInfo
      EqArgInfo = record { _==_ = eqArgInfo }

    unquoteDecl eqArg = derivingEq (quote Arg) eqArg

    instance
      EqArg : ∀ {A : Set} → {{_ : Eq A}} → Eq (Arg A)
      EqArg = record { _==_ = eqArg }

    unquoteDecl eqAbs = derivingEq (quote Abs) eqAbs

    instance
      EqAbs : ∀ {A : Set} → {{_ : Eq A}} → Eq (Abs A)
      EqAbs = record { _==_ = eqAbs }

    unquoteDecl eqLiteral = derivingEq (quote Literal) eqLiteral

    instance
      EqLiteral : Eq Literal
      EqLiteral = record { _==_ = eqLiteral }

    {-# TERMINATING #-}
    eqSort : (s₁ s₂ : Sort) → Dec (s₁ ≡ s₂)
    eqType : (ty₁ ty₂ : Type) → Dec (ty₁ ≡ ty₂)
    eqTerm : (t₁ t₂ : Term) → Dec (t₁ ≡ t₂)
    eqPattern : (p₁ p₂ : Pattern) → Dec (p₁ ≡ p₂)
    eqClause : (c₁ c₂ : Clause) → Dec (c₁ ≡ c₂)

    instance
      EqSort : Eq Sort
      EqSort = record { _==_ = eqSort }

      EqType : Eq Type
      EqType = record { _==_ = eqType }

      EqTerm : Eq Term
      EqTerm = record { _==_ = eqTerm }

      EqPattern : Eq Pattern
      EqPattern = record { _==_ = eqPattern }

      EqClause : Eq Clause
      EqClause = record { _==_ = eqClause }

    unquoteDef eqSort = deriveEqDef (quote Sort) (quote eqSort)
    unquoteDef eqType = deriveEqDef (quote Type) (quote eqType)
    unquoteDef eqTerm = deriveEqDef (quote Term) (quote eqTerm)
    unquoteDef eqPattern = deriveEqDef (quote Pattern) (quote eqPattern)
    unquoteDef eqClause = deriveEqDef (quote Clause) (quote eqClause)

**Comment by UlfNorell** [comment]
I believe the problem is that instance search is slowed down by duplicate instances. The `Eq` deriving already requires `Eq` instances for `Term`. Compare:

```agda
-- Fast
unquoteDecl EqTerm₁ =
  declareDef (vArg EqTerm₁) (quoteTerm (Eq Term)) >>
  defineEqInstance EqTerm₁ (quote Term)

-- Slow
unquoteDecl EqTerm₂ =
  declareDef (iArg EqTerm₂) (quoteTerm (Eq Term)) >>
  defineEqInstance EqTerm₂ (quote Term)
```

The only difference is that in the slow case we declare it an instance.
