### ISSUE TITLE
Applicative doesn't type check

### ISSUE THREAD

**Issue by bixuanzju** [UlfNorell/agda-prelude#48]
> Not in scope:
  ⦇
  at /Users/jeremybi/Projects/agda-prelude/src/Prelude/Applicative.agda:21,12-13
when scope checking ⦇
make: *** [compile-main] Error 1

**Comment by UlfNorell** [comment]
The master branch tracks the development version of Agda (currently [stable-2.5](https://github.com/agda/agda/tree/stable-2.5)). For Agda 2.5.1.* you need to use the [compat-2.5.1](../tree/compat-2.5.1) branch.

**Comment by bixuanzju** [comment]
Noted, thanks!
