### ISSUE TITLE
Latest agda breaks Prelude.Fin due to Irrelevance.

### ISSUE THREAD

**Issue by xekoukou** [UlfNorell/agda-prelude#58]
Typechecking Prelude.Fin does not work for latest agda. I hope this to be resolved as soon as @jespercockx finalizes his changes.

**Comment by jespercockx** [comment]
I created a PR (#59) to use the new `@erased` modality instead of `..`

**Comment by UlfNorell** [comment]
But didn't add a `fixes #X` commit message... I hope you ran the test suite this time :)

**Comment by watashiwa-toki** [comment]
But it still dont work. Windows 8.1, AGDA_PATH variable set to "C:\agdalib":

C:\agdalib\agda-prelude\src\Prelude\Fin.agda:17,15-15
C:\agdalib\agda-prelude\src\Prelude\Fin.agda:17,15: Parse error
@<ERROR>
erased n} → Fin n → Nat
finToN...

C:\agdalib\agda-prelude\src\Prelude\Fin.agda:17,15-15
C:\agdalib\agda-prelude\src\Prelude\Fin.agda:17,15: Parse error
@<ERROR>
Erased n} → Fin n → Nat
finToN...

**Comment by UlfNorell** [comment]
Looks like you are not using the development version of Agda. For Agda-2.5.4.* you should use the `compat-2.5.4` branch.

**Comment by watashiwa-toki** [comment]
With compat-2.5.4 branch works fine, thanks!
