### ISSUE TITLE
does not compile with Agda 2.6.0

### ISSUE THREAD

**Issue by lclem** [UlfNorell/agda-prelude#62]
This is the error I get:

``
agda-prelude/src/Numeric/Nat/Pow.agda:71,16-23
Invalid goal:
((_ Semiring.* a ^ (q +N q)) ((_ Semiring.* a) a) ≡
 (_ Semiring.* a ^ (q *N 2)) ((_ Semiring.* a) a))
when checking that the expression unquote auto has type
a ^ (q + q) * (a * a) ≡ a ^ (q * 2) * (a * a)
``

How could one fix it?

**Comment by UlfNorell** [comment]
I'll have a look.
