### ISSUE TITLE
Possible code merge

### ISSUE THREAD

**Issue by t-more** [UlfNorell/agda-prelude#70]
Hello, 

I've found myself preferring to use agda-prelude as the basis library for my hobby projects, but since it is missing a lot of proofs I started writing my own extension library. I though it may be of interest to integrate some of the things I've written here into the main library. (https://gitlab.com/tmore/agda-prelude-extras/-/tree/master/src/Prelude/Extras) 

I would probably have done so if there where any general guidlines on naming conventions and location of properties.
Would it be of interest if i merged some of the things from my library into the main one? And if so how would you prefer the directory structure and naming convention?

**Comment by UlfNorell** [comment]
I think many of your additions can go directly in the appropriate module. As for naming conventions there aren't any super strict ones. I've tried to avoid names like `a==?b⇒a≡b` but I'm not in principle against them. Why don't you make some PRs and we can discuss the particulars there.

**Comment by t-more** [comment]
Alright, I will do that.
