### ISSUE TITLE
Need help with List

### ISSUE THREAD

**Issue by notooth1** [UlfNorell/agda-prelude#82]
Hello,

I could not compile this code. Can anyone help?

```
module test1 where

open import Prelude

main : IO ⊤
main = let list : List String
           list = [ "0" , "1" ]
       in case index list 0 of λ where
            nothing  -> putStrLn "nothing"
            (just x) -> putStrLn x
```
output:
```
test1.agda:7,21-30
Σ _A_6 _B_7 !=< String
when checking that the inferred type of an application
  Σ _A_6 _B_7
matches the expected type
  String
```

**Comment by UlfNorell** [comment]
Agda doesn't have builtin list syntax. In your definition of `list`, the comma is the pair constructor and the list brackets is the `[_]` function that builds a singleton list, so the type checker is complaining that `String` is not the same as the dependent pair type `Σ`. This should work: `list = "0" ∷ "1" ∷ []`.

**Comment by notooth1** [comment]
That works. Thank you.
